package sap_api_output_formatter

type Header struct {
	InspectionPlanGroup            string `json:"InspectionPlanGroup"`
	InspectionPlan                 string `json:"InspectionPlan"`
	InspectionPlanInternalVersion  string `json:"InspectionPlanInternalVersion"`
	IsDeleted                      bool   `json:"IsDeleted"`
	BillOfOperationsDesc           string `json:"BillOfOperationsDesc"`
	Plant                          string `json:"Plant"`
	BillOfOperationsUsage          string `json:"BillOfOperationsUsage"`
	BillOfOperationsStatus         string `json:"BillOfOperationsStatus"`
	ResponsiblePlannerGroup        string `json:"ResponsiblePlannerGroup"`
	MinimumLotSizeQuantity         string `json:"MinimumLotSizeQuantity"`
	MaximumLotSizeQuantity         string `json:"MaximumLotSizeQuantity"`
	BillOfOperationsUnit           string `json:"BillOfOperationsUnit"`
	ReplacedBillOfOperations       string `json:"ReplacedBillOfOperations"`
	IsMarkedForDeletion            bool   `json:"IsMarkedForDeletion"`
	InspPlanHasMultipleSpec        string `json:"InspPlanHasMultipleSpec"`
	InspSubsetFieldCombination     string `json:"InspSubsetFieldCombination"`
	InspectionPartialLotAssignment string `json:"InspectionPartialLotAssignment"`
	SmplDrawingProcedure           string `json:"SmplDrawingProcedure"`
	SmplDrawingProcedureVersion    string `json:"SmplDrawingProcedureVersion"`
	InspectionLotDynamicLevel      string `json:"InspectionLotDynamicLevel"`
	InspLotDynamicRule             string `json:"InspLotDynamicRule"`
	InspExternalNumberingOfValues  string `json:"InspExternalNumberingOfValues"`
	CreationDate                   string `json:"CreationDate"`
	LastChangeDate                 string `json:"LastChangeDate"`
	ChangeNumber                   string `json:"ChangeNumber"`
	ValidityStartDate              string `json:"ValidityStartDate"`
	ValidityEndDate                string `json:"ValidityEndDate"`
	ChangedDateTime                string `json:"ChangedDateTime"`
}

type MaterialAssignment struct {
	Material                      string      `json:"Material"`
	Plant                         string      `json:"Plant"`
	InspectionPlanGroup           string      `json:"InspectionPlanGroup"`
	InspectionPlan                string      `json:"InspectionPlan"`
	InspPlanMatlAssignment        string      `json:"InspPlanMatlAssignment"`
	InspPlanMatlAssgmtIntVersion  string      `json:"InspPlanMatlAssgmtIntVersion"`
	InspectionPlanInternalVersion string      `json:"InspectionPlanInternalVersion"`
	ValidityStartDate             string      `json:"ValidityStartDate"`
	ValidityEndDate               string      `json:"ValidityEndDate"`
	ChangeNumber                  string      `json:"ChangeNumber"`
	CreationDate                  string      `json:"CreationDate"`
	LastChangeDate                string      `json:"LastChangeDate"`
	IsDeleted                     bool        `json:"IsDeleted"`
	Supplier                      string      `json:"Supplier"`
	Customer                      string      `json:"Customer"`
	MultipleSpecificationObject   string      `json:"MultipleSpecificationObject"`
	MultipleSpecificationObjType  string      `json:"MultipleSpecificationObjType"`
	BOOSearchText                 string      `json:"BOOSearchText"`
	ChangedDateTime               string      `json:"ChangedDateTime"`
}

type Operation struct {
	InspectionPlanGroup            string `json:"InspectionPlanGroup"`
	BOOOperationInternalID         string `json:"BOOOperationInternalID"`
	BOOCharacteristic              string `json:"BOOCharacteristic"`
	BOOCharacteristicVersion       string `json:"BOOCharacteristicVersion"`
	BOOOpInternalVersionCounter    string `json:"BOOOpInternalVersionCounter"`
	InspectionPlanInternalVersion  string `json:"InspectionPlanInternalVersion"`
	InspectionPlan                 string `json:"InspectionPlan"`
	ValidityStartDate              string `json:"ValidityStartDate"`
	ValidityEndDate                string `json:"ValidityEndDate"`
	ChangeNumber                   string `json:"ChangeNumber"`
	IsDeleted                      bool   `json:"IsDeleted"`
	BOOOperationPRTInternalID      string `json:"BOOOperationPRTInternalID"`
	InspectionMethod               string `json:"InspectionMethod"`
	InspectionMethodVersion        string `json:"InspectionMethodVersion"`
	InspectionMethodPlant          string `json:"InspectionMethodPlant"`
	InspSpecImportanceCode         string `json:"InspSpecImportanceCode"`
	InspectorQualification         string `json:"InspectorQualification"`
	InspectionSpecification        string `json:"InspectionSpecification"`
	InspectionSpecificationVersion string `json:"InspectionSpecificationVersion"`
	InspectionSpecificationPlant   string `json:"InspectionSpecificationPlant"`
	BOOCharcHasInspSpecReference   string `json:"BOOCharcHasInspSpecReference"`
	ProdnRsceToolItemNumber        string `json:"ProdnRsceToolItemNumber"`
	InspSpecControlIndicators      string `json:"InspSpecControlIndicators"`
	InspSpecIsQuantitative         string `json:"InspSpecIsQuantitative"`
	InspSpecIsMeasuredValueRqd     string `json:"InspSpecIsMeasuredValueRqd"`
	InspSpecIsSelectedSetRequired  string `json:"InspSpecIsSelectedSetRequired"`
	InspSpecIsUpperLimitRequired   string `json:"InspSpecIsUpperLimitRequired"`
	InspSpecIsLowerLimitRequired   string `json:"InspSpecIsLowerLimitRequired"`
	InspSpecIsTargetValueInLimit   string `json:"InspSpecIsTargetValueInLimit"`
	InspectionScope                string `json:"InspectionScope"`
	InspSpecIsLongTermInspection   string `json:"InspSpecIsLongTermInspection"`
	InspSpecRecordingType          string `json:"InspSpecRecordingType"`
	InspResultIsDocumentationRqd   string `json:"InspResultIsDocumentationRqd"`
	InspSpecCharcCategory          string `json:"InspSpecCharcCategory"`
	InspSpecIsSampleQtyAdditive    string `json:"InspSpecIsSampleQtyAdditive"`
	InspSpecIsDestructive          string `json:"InspSpecIsDestructive"`
	InspSpecResultCalculation      string `json:"InspSpecResultCalculation"`
	InspSpecIsSamplingProcedRqd    string `json:"InspSpecIsSamplingProcedRqd"`
	InspSpecIsScrapRelevant        string `json:"InspSpecIsScrapRelevant"`
	InspSpecHasFixedCtrlIndicators string `json:"InspSpecHasFixedCtrlIndicators"`
	InspSpecIsTestEquipmentRqd     string `json:"InspSpecIsTestEquipmentRqd"`
	InspSpecIsDefectRecordingRqd   string `json:"InspSpecIsDefectRecordingRqd"`
	InspSpecIsDefectsRecgAutomatic string `json:"InspSpecIsDefectsRecgAutomatic"`
	InspSpecIsChgDocRequired       string `json:"InspSpecIsChgDocRequired"`
	InspSpecIsControlChartUsed     string `json:"InspSpecIsControlChartUsed"`
	InspSpecPrintControl           string `json:"InspSpecPrintControl"`
	InspSpecFirstUpperSpecLimit    string `json:"InspSpecFirstUpperSpecLimit"`
	InspSpecHasFirstUpperSpecLimit string `json:"InspSpecHasFirstUpperSpecLimit"`
	InspSpecFirstLowerSpecLimit    string `json:"InspSpecFirstLowerSpecLimit"`
	InspSpecHasFirstLowerSpecLimit string `json:"InspSpecHasFirstLowerSpecLimit"`
	InspSpecSecondUpperSpecLimit   string `json:"InspSpecSecondUpperSpecLimit"`
	InspSpecHasSecondUprSpecLimit  string `json:"InspSpecHasSecondUprSpecLimit"`
	InspSpecSecondLowerSpecLimit   string `json:"InspSpecSecondLowerSpecLimit"`
	InspSpecHasSecondLowrSpecLimit string `json:"InspSpecHasSecondLowrSpecLimit"`
	InspSpecInputProcedure         string `json:"InspSpecInputProcedure"`
	InspSpecHasFormula             string `json:"InspSpecHasFormula"`
	InspSpecFormula1               string `json:"InspSpecFormula1"`
	InspSpecFormula2               string `json:"InspSpecFormula2"`
	InspSpecNumberOfClasses        int    `json:"InspSpecNumberOfClasses"`
	InspSpecClassWidthQty          string `json:"InspSpecClassWidthQty"`
	InspSpecHasClassWidth          string `json:"InspSpecHasClassWidth"`
	InspSpecClassMidpointQty       string `json:"InspSpecClassMidpointQty"`
	InspSpecHasClassMidpoint       string `json:"InspSpecHasClassMidpoint"`
	InspToleranceSpecification     string `json:"InspToleranceSpecification"`
	InspSpecDecimalPlaces          int    `json:"InspSpecDecimalPlaces"`
	InspectionSpecificationUnit    string `json:"InspectionSpecificationUnit"`
	InspSpecTargetValue            string `json:"InspSpecTargetValue"`
	InspSpecHasTargetValue         string `json:"InspSpecHasTargetValue"`
	InspSpecUpperLimit             string `json:"InspSpecUpperLimit"`
	InspSpecLowerLimit             string `json:"InspSpecLowerLimit"`
	InspSpecHasLowerLimit          string `json:"InspSpecHasLowerLimit"`
	InspSpecHasUpperLimit          string `json:"InspSpecHasUpperLimit"`
	InspSpecDefectCodeGrpRejection string `json:"InspSpecDefectCodeGrpRejection"`
	InspSpecDefectCodeRejection    string `json:"InspSpecDefectCodeRejection"`
	InspSpecDefectCodeGrpRjcnUpper string `json:"InspSpecDefectCodeGrpRjcnUpper"`
	InspSpecDefectCodeRjcnUpper    string `json:"InspSpecDefectCodeRjcnUpper"`
	InspSpecDefectCodeGrpRjcnLower string `json:"InspSpecDefectCodeGrpRjcnLower"`
	InspSpecDefectCodeRjcnLower    string `json:"InspSpecDefectCodeRjcnLower"`
	SelectedCodeSet                string `json:"SelectedCodeSet"`
	SelectedCodeSetPlant           string `json:"SelectedCodeSetPlant"`
	InspSpecAdditionalCatalog2     string `json:"InspSpecAdditionalCatalog2"`
	InspSpecAdditionalSelectedSet2 string `json:"InspSpecAdditionalSelectedSet2"`
	InspSpecAdditionalCodeGroup2   string `json:"InspSpecAdditionalCodeGroup2"`
	InspSpecAddlSeldCodeSetPlant2  string `json:"InspSpecAddlSeldCodeSetPlant2"`
	InspSpecAdditionalCatalog3     string `json:"InspSpecAdditionalCatalog3"`
	InspSpecAdditionalSelectedSet3 string `json:"InspSpecAdditionalSelectedSet3"`
	InspSpecAdditionalCodeGroup3   string `json:"InspSpecAdditionalCodeGroup3"`
	InspSpecAddlSeldCodeSetPlant3  string `json:"InspSpecAddlSeldCodeSetPlant3"`
	InspSpecAdditionalCatalog4     string `json:"InspSpecAdditionalCatalog4"`
	InspSpecAdditionalSelectedSet4 string `json:"InspSpecAdditionalSelectedSet4"`
	InspSpecAdditionalCodeGroup4   string `json:"InspSpecAdditionalCodeGroup4"`
	InspSpecAddlSeldCodeSetPlant4  string `json:"InspSpecAddlSeldCodeSetPlant4"`
	InspSpecAdditionalCatalog5     string `json:"InspSpecAdditionalCatalog5"`
	InspSpecAdditionalSelectedSet5 string `json:"InspSpecAdditionalSelectedSet5"`
	InspSpecAdditionalCodeGroup5   string `json:"InspSpecAdditionalCodeGroup5"`
	InspSpecAddlSeldCodeSetPlant5  string `json:"InspSpecAddlSeldCodeSetPlant5"`
	SamplingProcedure              string `json:"SamplingProcedure"`
	InspCharacteristicSampleUnit   string `json:"InspCharacteristicSampleUnit"`
	BOOCharcSampleQuantity         string `json:"BOOCharcSampleQuantity"`
	InspSpecInformationField1      string `json:"InspSpecInformationField1"`
	InspSpecInformationField2      string `json:"InspSpecInformationField2"`
	InspSpecInformationField3      string `json:"InspSpecInformationField3"`
	InspectionSpecificationText    string `json:"InspectionSpecificationText"`
	CreationDate                   string `json:"CreationDate"`
	LastChangeDate                 string `json:"LastChangeDate"`
	BillOfOperationsVersion        string `json:"BillOfOperationsVersion"`
	ChangedDateTime                string `json:"ChangedDateTime"`
}
